POST /tareas 
Content-Type: application/json
Host: localhost:3000

{
  "id": 4,
  "titulo": "Tarea 4",
  "descripcion": "Esta es una tarea de prueba para verificar el método POST",
  "completado": false
}

//envio par de datos y se almacena